### PR TITLE
Save stories as .html and add storycenter notebook

### PR DESCRIPTION
**Pull request by maltelueken**
I added a snippet to each notebook that saves the webpages as `.html` in case the webpages are taken down.

I found another great page with pandemic stories called [storycenter.org](https://www.storycenter.org/) and created a notebook to scrape and save the stories.

### CODE REVIEW

**Comment by ghost** [comment]
Nice find on storycenter.org Malte!

**Review by eriktks — CHANGES_REQUESTED** [review]
* Good that the retrieved files are being saved now. It would be even better if the notebooks also checked if the files were already downloaded and download them only if they are not on disk (otherwise read them from disk).

* The notebooks that store data should check if the data directories exist, otherwise the first run results in an error message:
```
import os
...
if not os.path.isdir(DATA_DIR):
    os.makedirs(DATA_DIR)
```

* the notebooks fetch the web pages twice, one for analysis and once for storage. This should be avoided, in order to not overload the websites

* the files are stored as byte strings, see `less ../psychologieheute.de/scraped/1.html` . I am not sure these stored files can be easily read back

**Comment by maltelueken** [comment]
Thanks for the suggestions!

I added a function to each notebook that checks if the files are already saved and load them instead of fetching the webpage if that is the case. I also added a check for the directory as you suggested.

> the notebooks fetch the web pages twice, one for analysis and once for storage. This should be avoided, in order to not overload the websites

I am not entirely sure what you mean by that. Now, the web page is only fetched once for storage I believe. Please correct me if I am wrong.

The files should be stored as strings now and can also be reloaded in the original format.

**Comment by maltelueken** [comment]
Oh, and I also formatted the notebooks to satisfy most pylint flags and enforced `pep8` style by using `nbqa autopep8 -i`.

**Review by eriktks — APPROVED** [review]
Thanks for the updates. All looks fine to me. Indeed, the urlopen function does not fetch the webpage, those were fetched by Request.

**Pull request merged**
